### ISSUE TITLE
Stubbing Aircloak resources during tests

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#12]
The exploration tool is going to rely quite heavily on the presence of the Aircloak APIs to extract data. This makes development and testing slow and complex. Particularly it makes it harder and slower to run automated tests (say from a CI environment).

Some languages support mocking out external resources by playing back the responses they would have yielded. And example is [VCR in ruby](https://github.com/vcr/vcr) which like the name suggests allows you to record the interactions with the real resource, and then later play it back again eliminating the need for the real resource when running tests.

Is there some equivalent in C#?
Alternatively, is there some tiny proxy one could use for these purposes?
Or, lacking something we can use off the shelf, maybe it would be worthwhile investing a little bit of time in an Aircloak API abstraction that can be used during testing that produces the expected results but without the runtime costs and overhead?

**Comment by dandanlen** [comment]
[This](https://github.com/mleech/scotch) is mentioned in the VCR github page and looks quite similar. Only issue I can see is that it records responses based on http verb and url. In other words, it won't distinguish between calls to the same endpoint but with different json payloads. 

In practice we can maybe work around this since the return data is accessed from a unique URL.

**Comment by AndreiBozantan** [comment]
I've found these two open source projects which are written in C# (if necessary we can make changes to fit our usage):
https://github.com/epignosisx/vcr.net
https://github.com/shiftkey/vcr-sharp

I will try to see how we can integrate one of these with our tests.

**Comment by AndreiBozantan** [comment]
closed with pull request #40
