### ISSUE TITLE
Version 0 of numerical column classification

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#13]
For numeric columns (integers as well as reals) I would like to see the first version produce the following values:

- minimum value
- maximum value
- average
- median 
- values for percentile histogram

**Comment by dandanlen** [comment]
I'll add some thoughts on this since I have already implemented this once (more or less):

## Min and Max Values

The naive (anonymized) `min` and `max` are not bad, however you can 'zoom in' and request the min and max over a narrow range to improve the estimate. 

For example using the [GiveMeSomeCredit](https://attack.aircloak.com/data_sources/GiveMeSomeCredit) data set:

```
SELECT min(MonthlyIncome), count(*)
FROM loans
```

Gives:
 
min | count
-- | --
6 543 | 150 000

We can take this result to zoom in further (the `count` is pretty high): 

```
SELECT min(MonthlyIncome), count(*)
FROM loans
WHERE MonthlyIncome BETWEEN 0 AND 6543
```

> Note the range will be [automatically adjusted](https://attack.aircloak.com/permalink/public/query/SFMyNTY.g3QAAAACZAAEZGF0YWgDZAAGcHVibGljZAAFcXVlcnltAAAAJDE3Nzg0YTYwLWJmNGYtNDViZC05ZTA0LWI2NzJhNTM1MjRiZmQABnNpZ25lZG4GAAYwMYxvAQ.xkq-LDWU8bGNC6v2WHoHtYpEJqpnPQ3W5wVdPtxpfLw) to `BETWEEN 0 AND 10000`

The new result is smaller than the last, the sample size is also smaller: 

min | count
-- | --
227 | 100 486

We can continue this process and in a couple more steps we get [this](https://attack.aircloak.com/permalink/public/query/SFMyNTY.g3QAAAACZAAEZGF0YWgDZAAGcHVibGljZAAFcXVlcnltAAAAJDkwZDRjODM4LWVkZTEtNDA1YS1iN2MxLTlhNGJjNjU2ZmZiYWQABnNpZ25lZG4GAFzRM4xvAQ.Eiy0HfhpvH0U0htuBUgPK5cihEmSMs3UKz_TIiil6WI)

```
SELECT min(MonthlyIncome), count(*)
FROM loans
WHERE MonthlyIncome BETWEEN 0 AND 2
```

Resulting in:

min | count
-- | --
0 | 2 237

This seems to be a simple way to get an improved estimate of the `min`. Something similar should be possible for `max` although I suspect that for most data set the values are the maximum are likely to be more dispersed (and thus the results noisier and less reliable). 

The downside of this approach is that is depends on multiple round-trips between the database and the client. The method could be improved by being more aggressive in estimating smaller bounds or performing some sort of binary search to find a narrow range that contains enough values to give reasonable results. 

Alternatively, wait until we have a good idea of the data distribution before estimating the range for calculating the `min` and `max`.

**Comment by dandanlen** [comment]
## Histogram

Getting a good histogram will be the foundation of everything else - we can use it to estimate the average, percentiles, median, min and max... 

The basis for the histogram will be counts of values in buckets (this pretty much the definition of a histogram...) so the basic query will be something like: 

```
SELECT 
    bucket(MonthlyIncome by 500),
    bucket(MonthlyIncome by 200),
    bucket(MonthlyIncome by 100),
    count(*),
    grouping_id(
        bucket(MonthlyIncome by 500),
        bucket(MonthlyIncome by 200),
        bucket(MonthlyIncome by 100)
    )
FROM 
    loans
GROUP BY GROUPING SETS (1,2,3)
```

(The `grouping_id` is necessary to identify the bucket size corresponding to each row.)

A basic pseudo-algorithm: 

1. Determine approximate bounds for the data set (use min and max). 
2. Based on these bounds, estimate a bucket size that gives sufficient resolution (say, each bucket ~1% of the data range). 
3. Choose a bucket size higher and lower than this estimated bucket size - the data might be more or less dense at different points in the data range and we want to get high resolution where we can (where the data is dense) and low resolution where the data is sparse to avoid suppressed rows. 
4. Query for counts in these three bucket sizes. 
5. Use the larger buckets to estimate any missing (suppressed) smaller buckets through interpolation (initially, for simplicity, this can be based on the assumption of an even distribution within each bucket). 

This works ok for columns with a reasonably even distribution. However in some cases it's not sufficient - for example the DebtRatio column in the GiveMeSomeCredit data set has most of it's values packed close to 0, and a veeery long tail of larger values. In this case the bucket sizes need to span multiple orders of magnitude to capture enough detail. 

> PS. I made some more notes on bucketing [here](https://github.com/diffix/explorer/wiki/Bucketing).

**Comment by sebastian** [comment]
Just a note: beware that columns and conditions each contribute noise layers (i.e. including a `WHERE`-clause `BETWEEN` filter will increase the distortion), and hence the amount of noise in the answer. It's a useful practice to get into to always also export a `*_noise` aggregate to ensure the results you get are sensible and not dominated by noise.

**Comment by dandanlen** [comment]
Yes, I started making notes in the wiki but then was unsure if that was the right place - particularly since there is no facility for discussion. I suppose the wiki should be more of a public resource rather than a place for development notes... For more development-focused stuff and particularly documentation, the repository itself is probably a better place. 

Getting off-topic here, but regarding documentation, does c# have anything for auto-generating docs similar to Python docstrings or Rust inline documentation?

**Comment by dandanlen** [comment]
Regarding the `*_noise` functions right now the only one of interest would be count_noise (min and max have no noise functions). Since in the bucketing queries we have no `WHERE` clauses (yet) the value of this is not so great IMO, at least at this stage of the project: It simply repeats the same constant for every row. But I suppose there's no harm in including it in the results.

**Comment by sebastian** [comment]
Aside: The `count_noise` aggregate function needs to be used in the same way as the `count` aggregate. I.e. `count(*)` paired with `count_noise(*)` and `count(distinct uid)` with `count_noise(distinct uid)`. 

The noise for `count(*)` is in fact very much not the same all the way! It is distribution dependent. Say you have a data set where there are multiple rows per user. Some users might have many rows, others fewer. The noise will scale to account for, and mask, those users with many rows. The noise value might therefore very well differ from row to row, and is unlikely going to stay at the same low constant value you most likely have mostly seen thus far.

I would suggest taking it into account sooner rather than later either way. It also helps make the decision whether further subdivision of a result makes sense at all or not. If the noise is more or less dominating the result, then subdividing makes little sense.

**Comment by dandanlen** [comment]
Ok thanks, that makes things much clearer 👍
