### ISSUE TITLE
Are docker images actually pushed to right location?

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#162]
When looking at the github actions it's clear that the images are being built and pushed, but when looking at the registry page of the repo, it says the last images is of may 11th?

https://github.com/diffix/explorer/packages/171341

**Comment by dandanlen** [comment]
I think the May 11th date refers to the most recent image actually tagged with a version number. 

Docker images are push by one of two actions:
1. Merging anything into the `master` branch creates an image tagged `latest` but doesn't tag any versions - this is for the hard-core bleeding-edge happy-go-lucky power-user 😉 
2. Declaring and tagging a `release` on github publishes an image with that release number.

I've published the latest *'Armstrong'* release as [`v0.1.4`](https://github.com/diffix/explorer/releases/tag/v0.1.4) so that if necessary this can be pinned to.
