### ISSUE TITLE
Git commit sha should not contain trailing +

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#235]
If I recall correctly from previous conversations it means there were pending changes locally, or some such?
It doesn't add any value to the reader to know this.

**Comment by dandanlen** [comment]
The value to the reader is that you can tell immediately by looking that there are local uncommitted changes, meaning it might be a development build. Otherwise you might go bug-hunting using the actual commit version. 

The reason this shows in production builds is that the `.gitignore` and `.dockerignore` files are not quite the same. 
So certain files that are part of the git repo are not copied to the docker image at build time, and git thinks there are pending changes... 

This latter issue has already been logged in #207 but short of making the .gitignore and .dockerignore files look the same (or remove the .dockerignore completely) I can't think of a proper solution.
